subreddits:
  - python
  - javascript
  - golang
  - rust
  - typescript
  - reactjs
  - django
  - flask
  - MachineLearning
  - dataengineering
  - apachekafka
  - docker
  - kubernetes
  - snowflake
  - databricks